### PR TITLE
feat(ob-sql-parser): make ob-sql-parser adapt to OceanBase 4.2

### LINKED ISSUE #312: [Bug]: syntax error when creating a table contains column with geometry datatype
### ODC version

ODC421

### OB version

Oceanbase4.1.0

### What happened?

There is a syntax error when creating a report, but the sql is executed successfully
image

### What did you expect to happen?

execution succeed

### How can we reproduce it (as minimally and precisely as possible)?

Execute the following sql
```SQL
create table if not exists `t1_g` (
	`id` int(11),
	`name` varchar(18),
	`g` geometry not null
)
default charset=utf8mb4
default collate=utf8mb4_general_ci;
create index `t1_g_idx1` on `t1_g` (`g` ASC);
```

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by yhilmare**
#### What type of PR is this?

type-feature

module-ob-sql-parser

#### What this PR does / why we need it:

OceanBase 4.2 was released not long ago. Some new syntaxes are allowed in OceanBase 4.2, so that we need to update our parser to adapt this.

#### Which issue(s) this PR fixes:

Fixes #312 #181  

#### Special notes for your reviewer:

We do these things as follow: 

**For MySQL Mode**

**New Syntax**

- create_dblink_stmt
- drop_dblink_stmt
- method_opt
- create_standby_tenant_stmt

**Refactor**

- supports interval time plus syntax.

eg.
```sql
select '2023-05-30' + interval 1 day from dual -- what we supports before 
select interval 1 day + '2023-05-12' from dual -- what we supports this time
```

- supports brace operator.

eg.
```sql
select {`ref_name` 1+1} from dual;
```

- supports several new functions: `bit_add`, `bit_or`, `bit_xor`, `point`, `linestring`, `multipoint`, `multilinestring`, `polygon`, `multipolygon`, `geometrycollection`, `geomcollection`, `check`.

- supports `with clause` for delete/update statement.
- supports `enable_arbitration_service`, `enable_extended_rowid` for tenant option.
- supports `external` reserved words for table creation and alter.

eg.
```sql
create external table test_tbl(id int);
alter external table test_tbl add column id int;
```

- supports partition options for index/unique key which is only supported by OceanBase

eg.
```sql
CREATE TABLE `index_part_tbl` (
	`id` INT(11) DEFAULT NULL,
	INDEX `id_idx`(`id`) PARTITION BY HASH(id) (PARTITION p0)
);
```

- supports index name setting for primary key

eg.
```SQL
create table pk_name_tbl(
    id int,
    primary key id_pk_tbl(id)
);
```

- supports setting constraint name and constraint state for check constraint at column and generated column attribute.

eg.
```SQL
CREATE TABLE check_col_attr_tbl (
	name VARCHAR(64) CONSTRAINT check_col_attr_tbl_1 CHECK(name IN ('David','Marry')),
    age int(11) generated always as (1+1) virtual constraint check_col_attr_tbl_2 check(age > 0) ENFORCED
)
```

- supports several geo datatype: `point`, `geometry`, `linestring`, `polygon`, `multipoint`, `multilinestring`, `multipolygon`, `geometrycollection`.
- supports several new character type: `mediumtext varchar`,` character`, `character`, `character`, `nchar`, `national character`, `varchar`, `nchar varchar`, `nvarchar`, `national varchar`, `character varying`, `national character varying`
- supports `location`, `format`, `pattern` for table options.
- supports `algorithm`, `definer` and `sql security` settings, view check options for view creation and alter.
- supports expression for index.

eg.
```SQL
CREATE TABLE T1 (
X1 VARCHAR(10),
X2 VARCHAR(10),
X3 VARCHAR(10),
X4 VARCHAR(10)
);

ALTER TABLE
T1
ADD
CONSTRAINT UNX_T1_EXPR UNIQUE(
(
case when (X1 = '1') then ((X2 || X3) || X4)
else NULL
end
)
);
```

- supports brace wrapped table reference.

eg.
```SQL
select * from {OJ tbl_name}
```

- supports dblink.

eg.
```SQL
select a from abcd@yausb
```

- supports straight_join.

eg.
```SQL
select col from ab straight_join b
```

- supports resource option setting when user created and altered.

**For Oracle Mode**

**New Syntax**

- create_context_stmt
- drop_context_stmt
- switchover_tenant_stmt
- recover_tenant_stmt

**Refactor**

- supports PLSQL variables, eg. `$$abcd`.
- supports json constraint check expression.

eg.
```SQL
'{"key": 123}' is not json format json strict allow scalars with unique keys
'{"key": 123}' is json format json lax disallow scalars without unique keys
```
- supports json_value, json_query, json_mergepatch, json_array, json_exists, json_object, json_table, json_arrayagg, json_objectagg functions.

eg.
```SQL
json_value('{"key":123}' format json, 'key' returning raw truncate ascii error_p on empty)
json_query('{"key":123}' format json, 'key' returning json truncate allow scalars pretty ascii with wrapper empty object on empty)
...
```
- supports json datatype.
- supports index subscript syntax.

eg.
```SQL
select a.b[*, 1, 2 to 3][1, 3] from tbl;
```
- Expand the way to access the custom type returned by the function. The content in the custom type can only be indexed numerically before. It can be indexed by any expression. At the same time, recursive access is also supported for new objects obtained by indexing.

```SQL
select func(1,2)(1)(3) from dual -> before
select func(1,2)('aaa')(12).abcd from dual -> after
```

-  supports xmlparse, xml_elemen, xml_extrace, xmlserialize, xmlcast functions.
- supports xmltype datatype.
- supports treat function.
- supports log error clause for delete/update statements.
- supports external reserved word when table created and altered. eg. `create external table xxx ...`.
- inline check constraint is allowed in column definition.
- location, format and pattern are added to table options.
- with check option is allowed when view created.
- with check option is allowed in select_from_clause.

eg. 
```SQL
select a from (select b from tbl with check option)
```

- add reversed link syntax in dblink

eg. 
```SQL
select a from abcd@remote!
```
- orderby and fetch next syntax are allowed in with_clause's cte.

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yizhouxw — DISMISSED** [review]
Exceptional contribution！

**Comment by yizhouxw** [comment]
how about add module level CHANGELOG for ob-sql-parser ?

**Review by smallsheeeep — APPROVED** [review]
Great job 👍

**Comment by yhilmare** [comment]
> how about add module level CHANGELOG for ob-sql-parser ?

😂I will do it when I was free

**Pull request merged**
