### PR TITLE
fix(connection): add serialVersionUID for ConnectionConfig

### LINKED ISSUE #1336: [Bug]: failed to approval or reject a ticket when ConnectionConfig has been changed
### ODC version

4.2.3

### OB version

not related

### What happened?

1. upgrade odc from 4.2.2 to 4.2.3
2. there are several tickets pending
3. approval or reject any one of them and an exception will be thrown:
```shell
详情
预期外异常，错误详情：Unhandled exception, type=PersistenceException, message= ### Error querying database. Cause: org.flowable.common.engine.api.FlowableException: Couldn't deserialize object in variable 'connectionConfig' ### Cause: org.flowable.common.engine.api.FlowableException: Couldn't deserialize object in variable 'connectionConfig'
```

### What did you expect to happen?

approval or reject the ticket normally

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by zijiacj**
#### What type of PR is this?
type-bug

#### Which issue(s) this PR fixes:

Fixes #1336

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yhilmare** [comment]
We can look again in FlowTaskUtil, there are other pojos that should do the same thing.

**Review by yhilmare — APPROVED** [review]
lgtm

**Review by krihy — COMMENTED** [review]
lgtm

**Review by krihy — DISMISSED** [review]

**Review by yhilmare — APPROVED** [review]
lgtm

**Review by yizhouxw — APPROVED** [review]
lgtm

**Review by smallsheeeep — APPROVED** [review]
lgtm

**Pull request merged**
