### PR TITLE
feat(db-browser): structural comparison task adaptation on ob-oracle mode in db-browser layer

### LINKED ISSUE #816: [Feature]: It is hoped that ODC could support structural comparison.
### Is your feature request related to a problem?

In daily work, I often need to ensure that the structures of development databases and test databases used for the same business are consistent, but because too many people use these two types of databases, I cannot determine whether their structures are truly consistent.

### Describe the solution you'd like

I hope that ODC could provide a method for comparing structures so that I can periodically check for differences between these two databases.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PeachThinking**
#### What type of PR is this?
type-feature
module-structure-comparison

#### What this PR does / why we need it:
This PR accomplishes 4 things：

1. Implement the following methods in `DBSchemaAccessor` for ob oracle mode to support ob oracle structure comparison:
```
Map<String, List<DBTableIndex>> listTableIndexes(String schemaName);
Map<String, List<DBTableConstraint>> listTableConstraints(String schemaName);
Map<String, DBTableOptions> listTableOptions(String schemaName);
```

2. Optimize SQL to query table index in ob oracle mode：
```
List<DBTableIndex> listTableIndexes(String schemaName, String tableName);
```
`list-table-indexes` statement and `list-index-columns` statement can be joined into one sql. 
Tested the performance after modifying sql in ob oracle 4.2.1 performance test environment：
before：
`list-table-indexes` sql costs about 26.799 sec.
`list-index-columns` sql costs about 17.848 sec.
after:
`list-table-indexes` sql costs about 39.094 sec;

3. The following operations are only supported by ob 4.x, so the implementation of `DBObjectEditor` differs between versions. Operations involving secondary partitions are not considered in this issue.
```
-- The following are operations that are not supported before ob mysql 4.x. 

-- add、delete primary key
ALTER TABLE `add_pk` ADD CONSTRAINT `add_pk_id` PRIMARY KEY (`id`) ;
ALTER TABLE `add_pk` DROP PRIMARY KEY;
ALTER TABLE `add_pk` ADD PRIMARY KEY (`id`);

-- Modify the partition type of a partitioned table
CREATE TABLE modify_hash_to_key(
    c1 int, 
    c2 datetime, 
    PRIMARY KEY(c1, c2)
) PARTITION BY HASH(c1) PARTITIONS 4;

ALTER TABLE modify_hash_to_key PARTITION BY KEY(c1) PARTITIONS 10;

-- Convert non-partitioned table to partitioned table
ALTER TABLE non_partition_to_partitioned PARTITION BY HASH(c1) partitions 4;

-- Modify the character set and collation of a table
ALTER TABLE `update_options` CHARACTER SET = gb18030;
ALTER TABLE `update_options` COLLATE = gb18030_chinese_ci;
```
```
-- The following are operations that are not supported by ob oracle before 4.x. 

-- add、delete primary key
ALTER TABLE "ADD_PK" ADD CONSTRAINT "ADD_PK_C1" PRIMARY KEY (C1) ;
ALTER TABLE "ADD_PK" DROP PRIMARY KEY;
ALTER TABLE "ADD_PK" ADD PRIMARY KEY (C1);

-- Convert non-partitioned table to partitioned table
ALTER TABLE non_partition_to_partition MODIFY PARTITION BY HASH(c1) PARTITIONS 4;
```

4. Fixed several issues：These bugs will not be triggered when editing table objects with ODC white screen because these operations are not supported:

- the ddl of ob mysql and ob oracle convert non-partitioned table to partition table is different:
```
-- ob mysql
ALTER TABLE table_name PARTITION BY partition_option;
-- ob oracle
ALTER TABLE table_name MODIFY PARTITION BY partition_option;
```

- The SQL generated by shadow table synchronization when convert **a partitioned table** to **a non-partitioned table** is incorrect: `alter table drop partition`, but in fact ob does not support converting a partitioned table into a non-partitioned table. But MySQL 5.7 support it: `ALTER TABLE table_name REMOVE PARTITIONING;` Fixed this bug in `DBTablePartitionEditor#handleUpdatePartitionType` method.
- The SQL generated by shadow table synchronization when convert **a non-partitioned table** to **a partitioned table** is incorrect: `alter table add partition`, correct sql is like: `ALTER TABLE non_partition_to_partition PARTITION BY HASH(c1) PARTITIONS 4;` Fixed this bug in `DBTablePartitionEditor#handleUpdatePartitionType` method.
- fix add primary key constraint ddl, if `!constraint.getName().isEmpty()` we should add `CONSTRAINT cons_name` in ddl, else we just  `ADD PRIMARY KEY` in ddl:
```
ALTER TABLE "ADD_PK" ADD CONSTRAINT "ADD_PK_C1" PRIMARY KEY (C1) ;
ALTER TABLE "ADD_PK" ADD PRIMARY KEY (C1);
```
- Unifiedly append ";\n" for the ddl generated by `DBObjectEditor#generateDropObjectDDL` and `DBObjectEditor#generateCreateObjectDDL`

#### Which issue(s) this PR fixes:

Fixes #816

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by MarkPotato777 — COMMENTED** [review]
Nice PR description! 👍🏻

**Review by MarkPotato777 — COMMENTED** [review]
Good job! I have no major issues with most of the content, however, there may be a performance issue within the `OBMySQLSchemaAccessor#listTableIndexes`. When we are obtaining the index range, we are going through the DDL query for all tables, even though the DDL may have already been retrieved in a previous step. If we could directly pass it down, it would significantly reduce the time cost. Could you help fix this performance issue? The related issue is https://github.com/oceanbase/odc/issues/1257

**Comment by PeachThinking** [comment]
> Good job! I have no major issues with most of the content, however, there may be a performance issue within the `OBMySQLSchemaAccessor#listTableIndexes`. When we are obtaining the index range, we are going through the DDL query for all tables, even though the DDL may have already been retrieved in a previous step. If we could directly pass it down, it would significantly reduce the time cost. Could you help fix this performance issue? The related issue is #1257

ok～Theoretically it can be optimized.

**Review by yhilmare — COMMENTED** [review]
lgtm

**Comment by yhilmare** [comment]
> > Good job! I have no major issues with most of the content, however, there may be a performance issue within the `OBMySQLSchemaAccessor#listTableIndexes`. When we are obtaining the index range, we are going through the DDL query for all tables, even though the DDL may have already been retrieved in a previous step. If we could directly pass it down, it would significantly reduce the time cost. Could you help fix this performance issue? The related issue is #1257
> 
> ok～Theoretically it can be optimized.

so, will you fix this issue in this pr or merge this pr first and fix the issue in another pr?

**Comment by PeachThinking** [comment]
> > > Good job! I have no major issues with most of the content, however, there may be a performance issue within the `OBMySQLSchemaAccessor#listTableIndexes`. When we are obtaining the index range, we are going through the DDL query for all tables, even though the DDL may have already been retrieved in a previous step. If we could directly pass it down, it would significantly reduce the time cost. Could you help fix this performance issue? The related issue is #1257
> > 
> > 
> > ok～Theoretically it can be optimized.
> 
> so, will you fix this issue in this pr or merge this pr first and fix the issue in another pr?

I will fix the issue in another pr.

**Review by yhilmare — APPROVED** [review]

**Pull request merged**
