### PR TITLE
fix(connect): sometimes open sql console result in 404 error

### PR DESCRIPTION
**Pull request by yhilmare**
#### What type of PR is this?

type-bug

#### What this PR does / why we need it:
use url base64 encoder or decoder to encode or decode the session id to avoid '/' char.
#### Which issue(s) this PR fixes:

Fixes #

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yhilmare** [comment]
https://stackoverflow.com/questions/43089541/difference-between-basic-and-url-base64-encoding-in-java-8

**Review by yizhouxw — APPROVED** [review]
lgtm,

i change the title, for match bug sceanario, not solution

**Review by LuckyPickleZZ — APPROVED** [review]
lgtm

**Comment by yhilmare** [comment]
ref: https://stackoverflow.com/questions/43089541/difference-between-basic-and-url-base64-encoding-in-java-8

**Pull request merged**
